name: sample_project_e
description: Emerlyn Interview Project
# version: 1.0.0
# homepage: https://www.example.com
# author: example <email@example.com>

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  csv: ^5.0.0

dev_dependencies:
  test: ^1.15.3
  mockito: ^4.1.3
  pedantic: ^1.9.0
